# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devCompChSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='元素名称')),
                ('content', models.FloatField(default=0, verbose_name='元素含量')),
                ('offset', models.FloatField(default=0, verbose_name='元素偏差值')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='devCompSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, verbose_name='物品名称及测量部位')),
                ('sampleID', models.CharField(max_length=10, verbose_name='样本编号')),
                ('inputDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入日期')),
                ('sampleState', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本状态')),
                ('sampleOrigin', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本产地')),
                ('sampleType', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本种类')),
                ('sampleMake', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本制备方法')),
                ('sampleDraw', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本提取方法')),
                ('sampleAnalyse', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本分析方法')),
                ('analyseCondition', models.CharField(blank=True, max_length=30, null=True, verbose_name='分析条件')),
                ('picUrl', models.ImageField(blank=True, null=True, upload_to='devCompSample/', verbose_name='爆炸装置样本外观图片路径')),
                ('picDescrip', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片描述')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='devCompSampleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectDevice', models.CharField(blank=True, max_length=30, null=True, verbose_name='检测设备名称及型号')),
                ('detectMrfs', models.CharField(blank=True, max_length=20, null=True, verbose_name='仪器厂家')),
                ('inputDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入日期')),
                ('detectType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='检测数据类型')),
                ('docType', models.IntegerField(blank=True, choices=[(1, 'txt'), (2, 'excel'), (3, 'PDF')], null=True, verbose_name='录入文档格式')),
                ('docUrl', models.FileField(blank=True, null=True, upload_to='devCompSampleFile/', verbose_name='录入文档路径')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='devCompSamplePeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peakStart', models.FloatField(default=0, verbose_name='起点')),
                ('peakEnd', models.FloatField(default=0, verbose_name='终点')),
                ('peakHeight', models.FloatField(default=0, verbose_name='峰高')),
                ('peakArea', models.FloatField(default=0, verbose_name='峰面积')),
            ],
        ),
        migrations.CreateModel(
            name='devShapeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCircuit', models.BooleanField(default=False, verbose_name='是否是电路板')),
                ('sname', models.CharField(max_length=20, verbose_name='装置名称')),
                ('sampleID', models.CharField(max_length=10, verbose_name='装置编号')),
                ('belongTo', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属装置')),
                ('inputDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入日期')),
                ('mrfs', models.CharField(blank=True, max_length=30, null=True, verbose_name='厂家')),
                ('sampleModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号')),
                ('trademark', models.CharField(blank=True, max_length=30, null=True, verbose_name='商标')),
                ('function', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属装置')),
                ('originalUrl', models.ImageField(blank=True, null=True, upload_to='devShapeSampleOriginal/', verbose_name='原始图像文件路径')),
                ('originalResolution', models.CharField(blank=True, max_length=30, null=True, verbose_name='原始图像采集分辨率')),
                ('nomUrl', models.ImageField(blank=True, null=True, upload_to='devShapeSampleNom/', verbose_name='归一化图像文件路径')),
                ('nomResolution', models.CharField(blank=True, max_length=30, null=True, verbose_name='归一化图像分辨率')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='exploChSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='元素名称')),
                ('content', models.FloatField(default=0, verbose_name='元素含量')),
                ('offset', models.FloatField(default=0, verbose_name='元素偏差值')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='exploSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10, verbose_name='样本名称')),
                ('sampleID', models.CharField(max_length=10, verbose_name='样本编号')),
                ('inputDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入日期')),
                ('sampleState', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本状态')),
                ('sampleOrigin', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本产地')),
                ('sampleType', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本种类')),
                ('sampleMake', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本制备方法')),
                ('sampleDraw', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本提取方法')),
                ('sampleAnalyse', models.CharField(blank=True, max_length=30, null=True, verbose_name='样本分析方法')),
                ('analyseCondition', models.CharField(blank=True, max_length=30, null=True, verbose_name='分析条件')),
                ('picUrl', models.ImageField(blank=True, null=True, upload_to='exploSample/', verbose_name='炸药外观图片路径')),
                ('picDescrip', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片描述')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='exploSampleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detectDevice', models.CharField(blank=True, max_length=30, null=True, verbose_name='检测设备名称及型号')),
                ('detectMrfs', models.CharField(blank=True, max_length=20, null=True, verbose_name='仪器厂家')),
                ('inputDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入日期')),
                ('detectType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='检测数据类型')),
                ('docType', models.IntegerField(blank=True, choices=[(1, 'txt'), (2, 'excel'), (3, 'PDF')], null=True, verbose_name='录入文档格式')),
                ('docUrl', models.FileField(blank=True, null=True, upload_to='exploSampleFile/', verbose_name='录入文档路径')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('exploSample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.exploSample', verbose_name='对应的炸药样本')),
            ],
        ),
        migrations.CreateModel(
            name='exploSamplePeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peakStart', models.FloatField(default=0, verbose_name='起点')),
                ('peakEnd', models.FloatField(default=0, verbose_name='终点')),
                ('peakHeight', models.FloatField(default=0, verbose_name='峰高')),
                ('peakArea', models.FloatField(default=0, verbose_name='峰面积')),
                ('exploSampleFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.exploSampleFile', verbose_name='对应的炸药文件')),
            ],
        ),
    ]
