# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20180430_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosamplefile',
            name='exploSample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploSampleFile', to='samples.exploSample', verbose_name='对应的炸药样本'),
        ),
    ]
