# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20180523_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devshapesample',
            name='nomUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeSample/nom/', verbose_name='归一化图像文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapesample',
            name='resultFileUrl',
            field=models.FileField(blank=True, null=True, upload_to='image/devShapeSample/original/', verbose_name='结果文件形式路径'),
        ),
    ]
