# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20180525_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devshapesample',
            name='originalUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeSample/original/', verbose_name='原始图像文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapesample',
            name='resultFileUrl',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='结果文件形式路径'),
        ),
    ]
