# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20180525_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devshapesample',
            name='isCircuit',
        ),
        migrations.AddField(
            model_name='devcompsamplefile',
            name='strength',
            field=models.CharField(default='千分之一', max_length=20, verbose_name='浓度'),
        ),
    ]
