# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20180508_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosamplefile',
            name='handledUrl',
            field=models.FilePathField(blank=True, null=True, path='F:\\毕设\\bishe430\\media\\file/exploSampleFile/handled/', verbose_name='处理完的文件'),
        ),
    ]
