# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20180528_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='devshapesample',
            name='isFirst',
            field=models.BooleanField(default=True, verbose_name='是否是第一次分割'),
        ),
    ]
