# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_devshapesample_isfirst'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosamplefile',
            name='strength',
            field=models.CharField(default='', max_length=20, verbose_name='浓度'),
        ),
        migrations.AlterField(
            model_name='devcompsamplefile',
            name='strength',
            field=models.CharField(default='', max_length=20, verbose_name='浓度'),
        ),
    ]
