# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20180512_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explosamplefile',
            name='handledUrl2',
        ),
        migrations.AlterField(
            model_name='devcompsamplefile',
            name='handledUrl',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='处理完的文件'),
        ),
    ]
