# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='image/test/', verbose_name='图片测试url'),
        ),
    ]
