# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_auto_20181015_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosamplefile',
            name='docUrl',
            field=models.FileField(blank=True, null=True, upload_to=samples.models.exploSampleFile.get_file_path, verbose_name='录入文档路径'),
        ),
    ]
