# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evis', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devCompMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='匹配数据类型')),
                ('matchModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='检测类型')),
                ('matchDegree', models.FloatField(default=0.0, verbose_name='匹配程度')),
                ('devCompEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchEvi', to='evis.devCompEvi', verbose_name='对应的物证')),
                ('devCompSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchSample', to='samples.devCompSample', verbose_name='对应的成分样本')),
            ],
            options={
                'verbose_name': '爆炸装置案件物证成分匹配结果表',
                'verbose_name_plural': '爆炸装置案件物证成分匹配结果表',
            },
        ),
        migrations.CreateModel(
            name='devShapeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchDegree', models.FloatField(default=0.0, verbose_name='得分')),
                ('matchCoordi', models.CharField(blank=True, max_length=400, null=True, verbose_name='匹配的位置坐标')),
                ('devShapeEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchEvi', to='evis.devShapeEvi', verbose_name='对应的物证')),
                ('devShapeSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchSample', to='samples.devShapeSample', verbose_name='对应的成分样本')),
            ],
            options={
                'verbose_name': '爆炸装置案件物证形态匹配结果表',
                'verbose_name_plural': '爆炸装置案件物证形态匹配结果表',
            },
        ),
        migrations.CreateModel(
            name='exploMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='匹配数据类型')),
                ('matchModel', models.CharField(blank=True, max_length=20, null=True, verbose_name='检测类型')),
                ('matchDegree', models.FloatField(default=0.0, verbose_name='匹配程度')),
                ('exploEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploMatchEvi', to='evis.exploEvi', verbose_name='对应的物证')),
                ('exploSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exploMatchSample', to='samples.exploSample', verbose_name='对应的样本')),
            ],
            options={
                'verbose_name': '炸药及原材料物证匹配结果表',
                'verbose_name_plural': '炸药及原材料物证匹配结果表',
            },
        ),
    ]
