# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0002_auto_20180430_1631'),
        ('evis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devCompMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='匹配数据类型')),
                ('matchDegree', models.IntegerField(default=0, verbose_name='匹配程度')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('devCompEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evis.devCompEvi', verbose_name='对应的物证')),
                ('devCompSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.devCompSample', verbose_name='对应的成分样本')),
            ],
        ),
        migrations.CreateModel(
            name='devShapeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchDegree', models.IntegerField(default=0, verbose_name='匹配程度')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('devShapeEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evis.devShapeEvi', verbose_name='对应的物证')),
                ('devShapeSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.devShapeSample', verbose_name='对应的成分样本')),
            ],
        ),
        migrations.CreateModel(
            name='exlpoMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchType', models.IntegerField(choices=[(1, 'FTIF'), (2, 'Raman'), (3, 'XRD'), (4, 'XRF'), (5, 'GC-MS')], verbose_name='匹配数据类型')),
                ('matchDegree', models.IntegerField(default=0, verbose_name='匹配程度')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('exploEvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evis.exploEvi', verbose_name='对应的物证')),
                ('exploSample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.exploSample', verbose_name='对应的样本')),
            ],
        ),
    ]
