# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devcompmatch',
            options={'verbose_name': '爆炸装置案件物证成分匹配结果表', 'verbose_name_plural': '爆炸装置案件物证成分匹配结果表'},
        ),
        migrations.AlterModelOptions(
            name='devshapematch',
            options={'verbose_name': '爆炸装置案件物证形态匹配结果表', 'verbose_name_plural': '爆炸装置案件物证形态匹配结果表'},
        ),
        migrations.AlterModelOptions(
            name='exlpomatch',
            options={'verbose_name': '炸药及原材料物证匹配结果表', 'verbose_name_plural': '炸药及原材料物证匹配结果表'},
        ),
    ]
