# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devshapematch',
            name='matchCoordi',
        ),
        migrations.AddField(
            model_name='devcompmatch',
            name='isSure',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
        migrations.AddField(
            model_name='devcompmatch',
            name='strength',
            field=models.CharField(default='千分之一', max_length=20, verbose_name='浓度'),
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='isCircuit',
            field=models.BooleanField(default=False, verbose_name='是否是元器件匹配'),
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='isSure',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='matchEviCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='匹配的物证位置坐标'),
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='matchSampleCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='匹配的样本位置坐标'),
        ),
        migrations.AddField(
            model_name='explomatch',
            name='isSure',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
    ]
