# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180528_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='explomatch',
            name='strength',
            field=models.CharField(default='', max_length=20, verbose_name='浓度'),
        ),
        migrations.AlterField(
            model_name='devcompmatch',
            name='strength',
            field=models.CharField(default='', max_length=20, verbose_name='浓度'),
        ),
    ]
