# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180430_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devcompmatch',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='devshapematch',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='exlpomatch',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='devshapematch',
            name='matchCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='匹配的位置坐标'),
        ),
        migrations.AlterField(
            model_name='devcompmatch',
            name='devCompEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchEvi', to='evis.devCompEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='devcompmatch',
            name='devCompSample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devCompMatchSample', to='samples.devCompSample', verbose_name='对应的成分样本'),
        ),
        migrations.AlterField(
            model_name='devcompmatch',
            name='matchDegree',
            field=models.FloatField(default=0.0, verbose_name='匹配程度'),
        ),
        migrations.AlterField(
            model_name='devshapematch',
            name='devShapeEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchEvi', to='evis.devShapeEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='devshapematch',
            name='devShapeSample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devShapeMatchSample', to='samples.devShapeSample', verbose_name='对应的成分样本'),
        ),
        migrations.AlterField(
            model_name='devshapematch',
            name='matchDegree',
            field=models.FloatField(default=0.0, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='exlpomatch',
            name='exploEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exlpoMatchEvi', to='evis.exploEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='exlpomatch',
            name='exploSample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exlpoMatchSample', to='samples.exploSample', verbose_name='对应的样本'),
        ),
        migrations.AlterField(
            model_name='exlpomatch',
            name='matchDegree',
            field=models.FloatField(default=0.0, verbose_name='匹配程度'),
        ),
    ]
