# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploevifile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='exploevi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='explochevi',
            name='exploEviFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploChEvi', to='evis.exploEviFile', verbose_name='对应的物证文件'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='devcompevipeak',
            name='devCompEviFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompEviPeak', to='evis.devCompEviFile', verbose_name='对应的物证文件'),
        ),
        migrations.AddField(
            model_name='devcompevifile',
            name='devCompEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompEviFile', to='evis.devCompEvi', verbose_name='对应的物证'),
        ),
        migrations.AddField(
            model_name='devcompevifile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='devcompevi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='处理人员'),
        ),
        migrations.AddField(
            model_name='devcompchevi',
            name='devCompEviFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompChEvi', to='evis.devCompEviFile', verbose_name='对应的物证文件'),
        ),
    ]
