# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evis', '0002_auto_20180430_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devcompchevi',
            options={'verbose_name': '爆炸装置案件物证成分子元素表', 'verbose_name_plural': '爆炸装置案件物证成分子元素表'},
        ),
        migrations.AlterModelOptions(
            name='devcompevi',
            options={'verbose_name': '爆炸装置案件物证成分表', 'verbose_name_plural': '爆炸装置案件物证成分表'},
        ),
        migrations.AlterModelOptions(
            name='devcompevifile',
            options={'verbose_name': '爆炸装置案件物证成分文件存储表', 'verbose_name_plural': '爆炸装置案件物证成分文件存储表'},
        ),
        migrations.AlterModelOptions(
            name='devcompevipeak',
            options={'verbose_name': '爆炸装置案件物证成分峰值表', 'verbose_name_plural': '爆炸装置案件物证成分峰值表'},
        ),
        migrations.AlterModelOptions(
            name='devshapeevi',
            options={'verbose_name': '爆炸装置案件物证形态表', 'verbose_name_plural': '爆炸装置案件物证形态表'},
        ),
        migrations.AlterModelOptions(
            name='explochevi',
            options={'verbose_name': '炸药及原材料案件物证子元素表', 'verbose_name_plural': '炸药及原材料案件物证子元素表'},
        ),
        migrations.AlterModelOptions(
            name='exploevi',
            options={'verbose_name': '炸药及原材料案件物证表', 'verbose_name_plural': '炸药及原材料案件物证表'},
        ),
        migrations.AlterModelOptions(
            name='exploevifile',
            options={'verbose_name': '炸药及原材料案件物证文件存储表', 'verbose_name_plural': '炸药及原材料案件物证文件存储表'},
        ),
        migrations.AlterModelOptions(
            name='exploevipeak',
            options={'verbose_name': '炸药及原材料案件物证峰值表', 'verbose_name_plural': '炸药及原材料案件物证峰值表'},
        ),
    ]
