# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evis', '0003_auto_20180523_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devshapeevi',
            name='isCircuit',
            field=models.BooleanField(default=False, verbose_name='是否是元器件匹配'),
        ),
    ]
