# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evis', '0003_auto_20180430_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devcompchevi',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='devcompevi',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='devcompevifile',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='devcompevipeak',
            name='peakEnd',
        ),
        migrations.RemoveField(
            model_name='devcompevipeak',
            name='peakStart',
        ),
        migrations.RemoveField(
            model_name='devshapeevi',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='explochevi',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='exploevi',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='exploevifile',
            name='isDelete',
        ),
        migrations.RemoveField(
            model_name='exploevipeak',
            name='peakEnd',
        ),
        migrations.RemoveField(
            model_name='exploevipeak',
            name='peakStart',
        ),
        migrations.AddField(
            model_name='devcompevifile',
            name='handledUrl',
            field=models.FileField(blank=True, null=True, upload_to='file/devCompEviFile/handled', verbose_name='处理完的文件'),
        ),
        migrations.AddField(
            model_name='devcompevipeak',
            name='peakPos',
            field=models.FloatField(default=0, verbose_name='峰高位置'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='backCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='背景颜色点坐标'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='blackWhiteUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeEvi/blackWhite/', verbose_name='黑白图像路径'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='boardCheckCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='主板像素坐标（校验）'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='boardCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='主板颜色点坐标'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='compCheckCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='元器件点坐标（校验）'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='featureUrl',
            field=models.FileField(blank=True, null=True, upload_to='file/devShapeEvi/feature', verbose_name='特征文件路径'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='interColorUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeEvi/interColor/', verbose_name='中间彩色图像路径'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='proCoordi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='前景颜色点坐标'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='rectCoordi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='矩形框坐标（4个）'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='resultFileUrl',
            field=models.FileField(blank=True, null=True, upload_to='file/devShapeEvi/result/', verbose_name='结果文件形式路径'),
        ),
        migrations.AddField(
            model_name='devshapeevi',
            name='resultPicUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeEvi/result/', verbose_name='结果图像形式路径'),
        ),
        migrations.AddField(
            model_name='exploevifile',
            name='handledUrl',
            field=models.FileField(blank=True, null=True, upload_to='file/exploEviFile/handled', verbose_name='处理完的文件'),
        ),
        migrations.AddField(
            model_name='exploevipeak',
            name='peakPos',
            field=models.FloatField(default=0, verbose_name='峰高位置'),
        ),
        migrations.AlterField(
            model_name='devcompchevi',
            name='devCompEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompChEvi', to='evis.devCompEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='devcompevifile',
            name='devCompEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompEviFile', to='evis.devCompEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='devcompevipeak',
            name='devCompEviFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devCompEviPeak', to='evis.devCompEviFile', verbose_name='对应的物证文件'),
        ),
        migrations.AlterField(
            model_name='devshapeevi',
            name='nomUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeEvi/nom/', verbose_name='归一化图像文件路径'),
        ),
        migrations.AlterField(
            model_name='devshapeevi',
            name='originalUrl',
            field=models.ImageField(blank=True, null=True, upload_to='image/devShapeEvi/original/', verbose_name='原始图像文件路径'),
        ),
        migrations.AlterField(
            model_name='explochevi',
            name='exploEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploChEvi', to='evis.exploEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='exploevifile',
            name='exploEvi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploEviFile', to='evis.exploEvi', verbose_name='对应的物证'),
        ),
        migrations.AlterField(
            model_name='exploevipeak',
            name='exploEviFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploEviPeak', to='evis.exploEviFile', verbose_name='对应的物证文件'),
        ),
    ]
