# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evis', '0004_auto_20180508_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcompevifile',
            name='handledUrl',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='处理完的文件'),
        ),
        migrations.AlterField(
            model_name='exploevifile',
            name='handledUrl',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='处理完的文件'),
        ),
    ]
