# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evis', '0005_auto_20180529_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='devshapeevi',
            name='isFirst',
            field=models.BooleanField(default=True, verbose_name='是否是第一次分割'),
        ),
    ]
